name: CI Worklfow
on:
  push:
   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
   build:
    name: Install dependencies npm
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18    

      - name: Install dependencies
        run: npm install

   trivy:
    name: Run Trivy (fs mode)
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

   despliegue:
    name: deploy
    runs-on: ubuntu-latest
    needs: [trivy]
    steps:
      - name: Deploy the thing
        run: |
          echo Deploying 🚀       

